HMSCore/Controllers/AboutUsController.cs
using HMSCore.Services;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;

namespace HMSCore.Controllers
{
    [Authorize]
    public class AboutUsController : Controller
    {
        private readonly IAboutUs aboutService;

        public AboutUsController(IAboutUs abService)
        {
            this.aboutService = abService;
        }

        public IActionResult AboutUs()
        {
            var aboutUs = this.aboutService.AboutUsData();

            return this.View(aboutUs);
        }
    }
}

HMSCore/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>@ViewData["Title"] - Hotel Management System</title>
    <link rel="icon" type="image/x-icon" href="~/assets/favicon.ico" />
    <link href="~/css/styles.css" rel="stylesheet" />
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />118
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <div class="d-flex" id="wrapper">
        <!-- Sidebar-->
        <div class="border-end bg-white" id="sidebar-wrapper">
            <div class="sidebar-heading border-bottom bg-light"><img src="~/images/hotelLogo.png" alt="Hotel logo" width="200" height="118" /></div>
            <div class="list-group list-group-flush">
                <a class="list-group-item list-group-item-action list-group-item-light p-3" asp-area="" asp-controller="Home" asp-action="Home">
                    <img class="navMenuIcon" src="~/images/homeButton.png" width="200" height="118" />Home
                </a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" asp-area="" asp-controller="Rooms" asp-action="All">
                    <img class="navMenuIcon" src="~/images/roomButton.png" width="200" height="118">Rooms
                </a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" asp-area="" asp-controller="RoomTypes" asp-action="All">
                    <img class="navMenuIcon" src="~/images/roomTypeButton.png" width="200" height="118">Room Types
                </a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" asp-area="" asp-controller="Reservations" asp-action="All">
                    <img class="navMenuIcon" src="~/images/reservationButton.png" width="200" height="118">Reservations
                </a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" asp-area="" asp-controller="Vouchers" asp-action="All">
                    <img class="navMenuIcon" src="~/images/voucherButton.png" width="200" height="118">Vouchers
                </a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" asp-area="" asp-controller="Guests" asp-action="All">
                    <img class="navMenuIcon" src="~/images/guestButton.png" width="200" height="118">Guests
                </a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" asp-area="" asp-controller="GuestRanks" asp-action="All">
                    <img class="navMenuIcon" src="~/images/guestRanksButton.png" width="200" height="118">Guest Ranks
                </a>
                <a class="list-group-item list-group-item-action list-group-item-light p-3" asp-area="" asp-controller="Invoices" asp-action="All">
                    <img class="navMenuIcon" src="~/images/invoiceButton.png" width="200" height="118">Invoices
                </a>
                @if (User.IsInRole("Admin"))
                {
                    <a class="list-group-item list-group-item-action list-group-item-light p-3" asp-area="Admin" asp-controller="Countries" asp-action="All">
                        <img class="navMenuIcon" src="~/images/settingsButton.png" width="200" height="118">System Settings
                    </a>
                }
                <a class="list-group-item list-group-item-action list-group-item-light p-3" asp-area="" asp-controller="AboutUs" asp-action="AboutUs">
                    <img class="navMenuIcon" src="~/images/aboutUsButton.png" width="200" height="118">About Us
                </a>
            </div>
        </div>
        <!-- Page content wrapper-->
        <div id="page-content-wrapper">
            <!-- Top navigation-->
            <nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
                <div class="container-fluid">
                    <button class="btn btn-light" id="sidebarToggle">
                        <img class="menuIcon" src="~/images/menuIcon.png" width="200" height="118" />

                    </button>
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"><span class="navbar-toggler-icon"></span></button>
                    <div class="collapse navbar-collapse" id="navbarSupportedContent">
                        <partial name="_LoginPartial" />
                    </div>
                </div>
            </nav>
            <!-- Page content-->
            <div class="container-fluid">
                @RenderBody()
            </div>
        </div>
    </div>

    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/js/scripts.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
    @await RenderSectionAsync("NavMenuArea", required: false)


    <!-- Bootstrap core JS-->
    <!--<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>-->
    <!-- Core theme JS-->
</body>
</html>